---
- hosts: localhost ansible_connection=local
  vars:
    master_user: "{{ hostvars[groups['kube-master'][0]]['ansible_user'] }}"
    master_ip: "{{ hostvars[groups['kube-master'][0]]['ip'] }}"
  tasks:
  - name: Kill existing forwards
    shell: "ps aux | grep -v grep | grep 8888:localhost:31000 | awk '{print $2}' | sudo xargs --no-run-if-empty kill -9"
  - name: Forward SSH port
    shell: "ssh -o StrictHostKeyChecking=no -fNT -L*:8888:localhost:31000 {{ master_user }}@{{ master_ip }}"

- hosts: kube-master[0]
  roles:
  - k8s-inception-ansible
  become: yes
...
