---
- name: apply kubectl service to create inception and notebook service
  command: |
    kubectl apply -f {{ role_path }}/files/{{ item }}
  with_items: "{{ inception_files }}"
  register: result
  changed_when: '"configured" in result.stdout or "created" in result.stdout'

- name: get notebook pod name
  command: |
    kubectl get pods -l run=tf-app -o custom-columns=:metadata.name --no-headers=true
  register: result
  changed_when: false

- name: set fact about pod name
  set_fact:
    pod_name: "{{ result.stdout_lines[-1] }}"

- name: pip install kubernetes and pillow inside the pod
  command: |
    kubectl exec {{ pod_name }} -- pip install kubernetes pillow
  register: result
  changed_when: '"Installing" in result.stdout'

- name: copy files to notebook container
  command: |
    kubectl cp {{ role_path}}/files/{{ item }} {{ pod_name }}:/tf/{{ item }}
  with_items:
    - k8s-inception-demo.ipynb
    - inception-client-job.yml
  changed_when: false

- name: get notebook token
  shell: |
    kubectl logs {{ pod_name }} | grep "token="
  register: notebook_token
  changed_when: false

- name: print notebook token
  debug: msg="{{ notebook_token.stdout_lines[-1] }}"
...
