---
apiVersion: v1
kind: Service
metadata:
  name: tf-app
  labels:
    run: tf-app
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 31000
  selector:
    run: tf-app
...
